using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace FairMount_api.Models.Tables
{
    [Table("PackingList")]
    public class PackingList
    {
        [Key]
        public int PackingListId { get; set; }  // Auto-generated by DB

        [Column("CommercialInvoiceId")]
        [Required]
        public int CommercialInvoiceId { get; set; }

        [Column("CommercialInvoiceNumber")]
        [Required]
        public string CommercialInvoiceNumber { get; set; } = string.Empty;

        // 🔗 Organizations
        [Column("CustomerOrgId")]
        [Required]
        public int CustomerId { get; set; }

        [Column("ShipperOrgId")]
        [Required]
        public int ShipperId { get; set; }

        [Column("ShipToAddress")]
        [Required]
        public int ShipToId { get; set; }

        // General Packing List Details
        [Column("CreatedAt")]
        [Required]
        public DateTime CreatedAt { get; set; }

        [Column("Currency")]
        public string? Currency { get; set; } = "USD";

        [Column("TermsOfSale")]
        public string? TermsOfSale { get; set; }

        [Column("TermsOfPayment")]
        public string? TermsOfPayment { get; set; }

        [Column("TermsOfShipping")]
        public string? TermsOfShipping { get; set; }

        [Column("ModeOfTransport")]
        public string? ModeOfTransport { get; set; }

        [Column("PlaceOfReceipt")]
        public string? PlaceOfReceipt { get; set; }

        [Column("FinalDestination")]
        public string? FinalDestination { get; set; }

        [Column("ContactName")]
        public string? ContactName { get; set; }

        [Column("ContactNo")]
        public string? ContactNo { get; set; }

        [Column("TaxId")]
        public string? TaxId { get; set; }

        [Column("Ein")]
        public string? Ein { get; set; }

        [Column("Email")]
        public string? Email { get; set; }

        [Column("Email2")]
        public string? Email2 { get; set; }

        [Column("Note")]
        public string? Note { get; set; }

        [Column("CreatedBy")]
        public int? CreatedBy { get; set; }


        [Column("BillOfLading")]
        public string? BillOfLading{ get; set; }

        [Column("AWBNo")]
        public string? AWBNo { get; set; }

        [Column("NumberOfBoxes")]
        public int? NumberOfBoxes { get; set; }

        [Column("NumberOfPallets")]
        public int? NumberOfPallets { get; set; }

        [Column("GrossWeight")]
        public decimal? GrossWeight { get; set; }

        [Column("MarkAndNumber")]
        public string? MarkAndNumber { get; set; }

        [Column("K11")]
        public string? K11 { get; set; }


        public ICollection<PackingListItem> PackingListItems { get; set; } = new List<PackingListItem>();
    }
}
